[google_service_account]
type = "service_account"
project_id = "evocative-shore-476022-d8"
private_key_id = "9960ab7fd93b7ce59243fae89144094c83839e59"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuytBEpCl4P2GT
7cY5JtUrolD/8Z/T6luQnG7Qz2rvGwATjwMoEBU1dkRLKG+bdGmkD76j+uVVrR+x
0LFTWfzCjaweony9OUjXRw+i9EGDZEERlufYmTVgIqMLO4n483onM53LFUPMhRPW
MV8xv2D93Co1MSu60qr6jZQUA/UZhWqwZ9jogQubhdD//vmcpiGbEErYL9KXmFbr
vRQEiKVAVRyZFuWumRI+Gu25Jq9BYLNkfzpLz5toOzZYpwI9E0q+ddbDvpBNLoBq
QBcmZRPggMN9YW3874HYpb4uMuyDVeEqPXlSsascIcT1l+gwcz3yZDiQzvPnVVWP
zkSMCvKVAgMBAAECggEAPDQ1Cf91HSrPhDE4vkSm1dGhjpZ903L8ONH4xUk77sFh
BFuU3b60X2at3Sk/T88H9+9IXZi0Vw87RHa6LRhom+ZKK38R8ecCNMwQEbOJwSTN
2K4eixcyMDud5ueJ/Up3f3si1WksogwQKg11WWAumyGzFAEsq7uWEpijMUWvrSsa
PG8EikVyY2UcXQvhks/SGeYC7CmmHDJoreup/nkd98al6/uEiiH37GHY86YJBYu8
EqCJ+BEEj3sXUi4zdZFM5XMi2Vr8AOl1WBBFODVn6sc9EJHrbJvoN5vHW6nyVENF
Thq5fjGJ/9Fj+gYEOcpNYZ+lyN8xcadFCkQRp0Hh/QKBgQDUjaLwtQ7GTybGHQsi
5o9MCsSpbBs0loaTulrnT88Pbgqieg/12p5aRWfnhOcZnW9Cr45kNd2acHPzv5fN
vssAHA3fTOe1zYd4qMX8apFHJmf8g8JOIBmYy4AojFKBkFTMYirclzLX2R6vdAC8
ZGx45UYBmCfW+D5s5ubum92ZGwKBgQDShT1zXOXW094e+Dm0FztI/s/hOX5HLerG
CScz1n9D0OZ8rVcQ+GmE95RDggCW0DLKlHnXBSkrqTkr1V1k1Mhk3nHl4U9wJ8nj
uxuS+glw7lH7oij8SpQZwUl6pak7jYp+UQPFfim7TjlOvU0FWm3eYGIY452SWU/4
AmfLwYaODwKBgAHtLrbjzTh66y0MgldUo6PazSGD+1Mksh+QptZF4OiQ5MPIO3DN
BHZo/qIYkEepJ6MBGFdMLbACqOpiqCuTOR/NIUsO1WLOdBXh4bmB9cMhU/vz7cTr
gY/i+ExlyTGnbz1S/nR1Yl6WdzK76G3Mszb9TP8is+m84kP2a81p2D5VAoGBAIve
2OhIJbEpTWA4PmaINOyX2FhlEaCLQnxXYoOPlTjil/DoXnu5AKrGr+x2eJu7MrPk
GFujYypOId0cwxOWSJq0LOq2W0hCN2ImU/jARfuRbEkLAb42ctX11TM21AzsSsMI
YsAZxfJb07mcDotq/KqOUT8GJBAzZO1786iuKQ9DAoGBAJQ2+CADcTZkcLQ70mUp
jWFozhvDzSJYI3fPeONWwAlNQfQwHliw/NNSBH60rw15I9eY5Ojq6t4SOaQYtQ8g
UcqtJpaqbCo1tbOOZLJmL6DqPZIz75zPnrHRooeW+gVPlLXH5q0uzNymMSUSGMzO
8vFGN8aOPGUQQ/uWVNd5FIa2
-----END PRIVATE KEY-----"""
client_email = "streamlit-app-942@evocative-shore-476022-d8.iam.gserviceaccount.com"
client_id = "103258256065312179065"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app-942%40evocative-shore-476022-d8.iam.gserviceaccount.com"

[spreadsheet]
sheet_id = "15SQy7BW112l1EHWZU37YpxA-Z-ZNwuzGXmllJ-JuM_Y"


